### create a libraryEvent
POST http://localhost:8080/api/libraryevent
Content-Type: application/json

{
  "libraryEventId": 4,
  "book": {
    "bookId": "104",
    "bookName": "Kafka using springboot",
    "bookAuthor": "Dilip"
  }
}
