### create a libraryEvent
POST http://localhost:8080/api/libraryevent
Content-Type: application/json

{
  "libraryEventId": 7,
  "book": {
    "bookId": "100",
    "bookName": "Kafka using springboot",
    "bookAuthor": "Dilip"
  }
}
