spring:
  profiles:
    active: local

---
server:
  port: 8080
spring:
  banner:
    image:
      location: classpath:banner.jpg
      margin: 85
      height: 15
      width: 30
      pixelmode: text
      bitdepth: 8
      invert: off
  application:
    name: "kafka-producer-ca"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  kafka:
    template:
      default-topic: library-events
    producer:
      bootstrap-servers: localhost:8097, localhost:8098, localhost:8099
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
    admin:
      properties:
        bootstrap.servers: localhost:8097, localhost:8098, localhost:8099
  config:
    activate:
      on-profile: local
management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true
app:
  kafka:
    default-topic: library-events
---
server:
  port: 8080
spring:
  application:
    name: "kafka-producer-ca"
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true
logging:
  level:
    web: debug
app:
  kafka:
    default-topic: library-events
