spring:
  profiles:
    active: local

---
server:
  port: 8080
spring:
  application:
    name: "kafka-producer-ca"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  config:
    activate:
      on-profile: local
management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true
logging:
  level:
    web: debug
---
server:
  port: 8080
spring:
  application:
    name: "kafka-producer-ca"
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true
logging:
  level:
    web: debug
